export const Assets = {
  General: {
    Contato: "/contato-kaique-mesa.webp",
    KaiqueCompetidor: "/kaique-competidor.png",
  },
  Skills: {
    Docker: "/img-skills/docker.svg",
    Kafka: "/img-skills/kafka.svg",
    AWS: "/img-skills/aws.svg",
    PostgreSQL: "/img-skills/postgresql.svg",
    Java: "/img-skills/java.webp",
    Firebase: "/img-skills/firebase.webp",
    Flutter: "/img-skills/flutter.webp",
    Git: "/img-skills/git.webp",
    Github: "/img-skills/github.webp",
    Spring: "/img-skills/springboot.webp",
    Angular: "/img-skills/angular.webp",
    Next: "/img-skills/nextjs.webp",
    Node: "/img-skills/nodejs.webp",
    React: "/img-skills/react.webp",
    SQL: "/img-skills/sql_server.webp",
    Tailwind: "/img-skills/tailwind.webp",
    TS: "/img-skills/typescript.webp",
    HTML: "/img-skills/html.webp",
    CSS: "/img-skills/css.webp",
    JS: "/img-skills/javascript.webp",
  },
  Projects: {
    Agita: "/img-projects/agita-senai-cover.webp",
    Amazon: "/img-projects/amazon-scraper-cover.webp",
    Finance: "/img-projects/controle-financeiro.webp",
    HBU: "/img-projects/hbu.webp",
    MindTask: "/img-projects/mind-task-cover.webp",
    Olx: "/img-projects/olx-cover.webp",
    PetDev: "/img-projects/pet-dev-cover.webp",
    Uber: "/img-projects/uber-cover.webp",
  },
  Institutions: {
    MyData: "/img-instituicoes/mydata.webp",
    Nuclea: "/img-instituicoes/nuclea.webp",
    Senai: "/img-instituicoes/senai.webp",
    Unimar: "/img-instituicoes/unimar.webp",
    WorldSkills: "/img-instituicoes/world-skills.webp",
  },
};
